version: '3'

networks:
  laravel_base:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx_base
    ports:
      - 8004:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel_base
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mariadb:10.6
    container_name: mysql_base
    restart: unless-stopped
    tty: true
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: altech_omega_andalan
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel_base

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php_base
    volumes:
      - ./src:/var/www/html:delegated
      - ./dockerfiles/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_base
    extra_hosts:
      - "host.docker.internal:host-gateway"

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer_base
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer']
    networks:
      - laravel_base

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan_base
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel_base
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    container_name: redis_base
    ports:
      - 63791:6379
    networks:
      - laravel_base